# Generated by Django 2.0.6 on 2018-07-02 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=68)),
                ('apellido', models.TextField(max_length=68)),
                ('direccion', models.TextField(max_length=100)),
                ('telefono', models.PositiveIntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('contra', models.TextField(max_length=42)),
                ('genero', models.TextField(max_length=20)),
                ('nacimiento', models.DateField()),
                ('cui', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.Pais'),
        ),
        migrations.AddField(
            model_name='admin',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.Municipio'),
        ),
    ]
