# Generated by Django 2.0.6 on 2018-07-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='apellido',
            field=models.CharField(max_length=68),
        ),
        migrations.AlterField(
            model_name='admin',
            name='contra',
            field=models.CharField(max_length=42),
        ),
        migrations.AlterField(
            model_name='admin',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='admin',
            name='genero',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='admin',
            name='nombre',
            field=models.CharField(max_length=68),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
    ]
