# Generated by Django 2.0.6 on 2018-07-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_auto_20180702_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='nombre',
            field=models.TextField(max_length=68),
        ),
    ]
