# Generated by Django 2.0.6 on 2018-07-04 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_auto_20180704_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='municipio',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
