# Generated by Django 2.0.6 on 2018-07-05 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_auto_20180704_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=68)),
                ('apellido', models.CharField(max_length=68)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.PositiveIntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('contra', models.CharField(max_length=42)),
                ('genero', models.CharField(max_length=20)),
                ('nacimiento', models.DateField()),
                ('cui', models.PositiveIntegerField()),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.Municipio')),
            ],
        ),
    ]
