# Generated by Django 2.0.6 on 2018-07-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_administrador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='cui',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
