# Generated by Django 2.0.6 on 2018-07-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_auto_20180706_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='usrtkn',
            field=models.CharField(default=10, max_length=30),
            preserve_default=False,
        ),
    ]
