# Generated by Django 2.0.6 on 2018-07-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_administrador_usrtkn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='contra',
            field=models.CharField(max_length=120),
        ),
    ]
