# Generated by Django 2.0.6 on 2018-07-08 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0008_auto_20180707_0435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('apellido', models.CharField(max_length=128)),
                ('nacimiento', models.DateField()),
                ('fallecimiento', models.DateField()),
                ('fecha_ingreso', models.DateField()),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.Pais')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('existencia', models.PositiveIntegerField()),
                ('ubicacion', models.TextField()),
                ('fecha_ingreso', models.DateField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.Autor')),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=82)),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='libro',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.Tema'),
        ),
    ]
