# Generated by Django 2.0.6 on 2018-07-18 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0009_auto_20180708_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='libro',
            name='biblioteca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admins.Biblioteca'),
            preserve_default=False,
        ),
    ]
