# Generated by Django 2.0.6 on 2018-07-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180707_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usrtkn',
            field=models.CharField(default=10, max_length=30),
            preserve_default=False,
        ),
    ]
