# Generated by Django 2.0.6 on 2018-07-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_usrtkn'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imagen',
            field=models.TextField(default=10),
            preserve_default=False,
        ),
    ]
