# Generated by Django 2.0.6 on 2018-07-10 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0009_auto_20180708_1809'),
        ('user', '0005_remove_user_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('estado', models.BooleanField()),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.Libro')),
            ],
        ),
    ]
