# Generated by Django 2.0.6 on 2018-07-11 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_prestamo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.Municipio'),
        ),
    ]
